import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { SocketProvider } from "../context/SocketProvider";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "@/context/AuthProvider";
import React from "react";
import Navbar from "@/components/navbar";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SocketProvider>
      <AuthProvider>
        <Navbar/>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Toaster />
        {children}
      </body>
      </AuthProvider>
      </SocketProvider>
    </html>
  );
}
